version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: unless-stopped
