[tool.black]
line-length = 100
target-version = ["py39"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true
force_sort_within_sections = true
known_first_party = ["app"]
sections = ["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
include_trailing_comma = true
multi_line_output = 3

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
exclude = [".git", "__pycache__", ".venv", "venv", ".mypy_cache", ".pytest_cache"]